#ifndef __ERROR_H__
#define __ERROR_H__

#include <stdio.h> 
#ifdef EXTENDED_STATUS_CODES
typedef enum status_code {
    STATUS_CONTINUE = 100,
    STATUS_SWITCHING_PROTOCOLS = 101,
    STATUS_PROCESSING = 102,
    STATUS_EARLY_HINTS = 103,

    STATUS_OK = 200,
    STATUS_CREATED = 201,
    STATUS_ACCEPTED = 202,
    STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
    STATUS_NO_CONTENT = 204,
    STATUS_RESET_CONTENT = 205,
    STATUS_PARTIAL_CONTENT = 206,
    STATUS_MULTI_STATUS = 207,
    STATUS_ALREADY_REPORTED = 208,
    STATUS_IM_USED = 226,

    STATUS_MULTIPLE_CHOICES = 300,
    STATUS_MOVED_PERMANENTLY = 301,
    STATUS_FOUND = 302,
    STATUS_SEE_OTHER = 303,
    STATUS_NOT_MODIFIED = 304,
    STATUS_USE_PROXY = 305,
    STATUS_TEMPORARY_REDIRECT = 307,
    STATUS_PERMANENT_REDIRECT = 308,

    STATUS_BAD_REQUEST = 400,
    STATUS_UNAUTHORIZED = 401,
    STATUS_PAYMENT_REQUIRED = 402,
    STATUS_FORBIDDEN = 403,
    STATUS_NOT_FOUND = 404,
    STATUS_METHOD_NOT_ALLOWED = 405,
    STATUS_NOT_ACCEPTABLE = 406,
    STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
    STATUS_REQUEST_TIMEOUT = 408,
    STATUS_CONFLICT = 409,
    STATUS_GONE = 410,
    STATUS_LENGTH_REQUIRED = 411,
    STATUS_PRECONDITION_FAILED = 412,
    STATUS_PAYLOAD_TOO_LARGE = 413,
    STATUS_URI_TOO_LONG = 414,
    STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
    STATUS_RANGE_NOT_SATISFIABLE = 416,
    STATUS_EXPECTATION_FAILED = 417,
    STATUS_IM_A_TEAPOT = 418,
    STATUS_MISDIRECTED_REQUEST = 421,
    STATUS_UNPROCESSABLE_ENTITY = 422,
    STATUS_LOCKED = 423,
    STATUS_FAILED_DEPENDENCY = 424,
    STATUS_TOO_EARLY = 425,
    STATUS_UPGRADE_REQUIRED = 426,
    STATUS_PRECONDITION_REQUIRED = 428,
    STATUS_TOO_MANY_REQUESTS = 429,
    STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,

    STATUS_INTERNAL_SERVER_ERROR = 500,
    STATUS_NOT_IMPLEMENTED = 501,
    STATUS_BAD_GATEWAY = 502,
    STATUS_SERVICE_UNAVAILABLE = 503,
    STATUS_GATEWAY_TIMEOUT = 504,
    STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
    STATUS_VARIANT_ALSO_NEGOTIATES = 506,
    STATUS_INSUFFICIENT_STORAGE = 507,
    STATUS_LOOP_DETECTED = 508,
    STATUS_NOT_EXTENDED = 510,
    STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511
} status_code_t;
#else
typedef enum status_code {
    STATUS_OK = 200,
    STATUS_BAD_REQUEST = 400,
    STATUS_FORBIDDEN = 403,
    STATUS_NOT_FOUND = 404,
    STATUS_METHOD_NOT_ALLOWED = 405,
    STATUS_URI_TOO_LONG = 414,
    STATUS_INTERNAL_SERVER_ERROR = 500,
    STATUS_NOT_IMPLEMENTED = 501,
} status_code_t;
#endif /* EXTENDED_STATUS_CODES */

#ifdef EXTENDED_STATUS_CODES
typedef struct response_status_code {
    status_code_t code;
    const char *reason_phrase;
} response_status_code_t;


static const response_status_code_t response_status_codes[] = {
    { STATUS_CONTINUE, "Continue" },
    { STATUS_SWITCHING_PROTOCOLS, "Switching Protocols" },
    { STATUS_PROCESSING, "Processing" },
    { STATUS_EARLY_HINTS, "Early Hints" },

    { STATUS_OK, "OK" },
    { STATUS_CREATED, "Created" },
    { STATUS_ACCEPTED, "Accepted" },
    { STATUS_NON_AUTHORITATIVE_INFORMATION, "Non-Authoritative Information" },
    { STATUS_NO_CONTENT, "No Content" },
    { STATUS_RESET_CONTENT, "Reset Content" },
    { STATUS_PARTIAL_CONTENT, "Partial Content" },
    { STATUS_MULTI_STATUS, "Multi-Status" },
    { STATUS_ALREADY_REPORTED, "Already Reported" },
    { STATUS_IM_USED, "IM Used" },

    { STATUS_MULTIPLE_CHOICES, "Multiple Choices" },
    { STATUS_MOVED_PERMANENTLY, "Moved Permanently" },
    { STATUS_FOUND, "Found" },
    { STATUS_SEE_OTHER, "See Other" },
    { STATUS_NOT_MODIFIED, "Not Modified" },
    { STATUS_USE_PROXY, "Use Proxy" },
    { STATUS_TEMPORARY_REDIRECT, "Temporary Redirect" },
    { STATUS_PERMANENT_REDIRECT, "Permanent Redirect" },

    { STATUS_BAD_REQUEST, "Bad Request" },
    { STATUS_UNAUTHORIZED, "Unauthorized" },
    { STATUS_PAYMENT_REQUIRED, "Payment Required" },
    { STATUS_FORBIDDEN, "Forbidden" },
    { STATUS_NOT_FOUND, "Not Found" },
    { STATUS_METHOD_NOT_ALLOWED, "Method Not Allowed" },
    { STATUS_NOT_ACCEPTABLE, "Not Acceptable" },
    { STATUS_PROXY_AUTHENTICATION_REQUIRED, "Proxy Authentication Required" },
    { STATUS_REQUEST_TIMEOUT, "Request Timeout" },
    { STATUS_CONFLICT, "Conflict" },
    { STATUS_GONE, "Gone" },
    { STATUS_LENGTH_REQUIRED, "Length Required" },
    { STATUS_PRECONDITION_FAILED, "Precondition Failed" },
    { STATUS_PAYLOAD_TOO_LARGE, "Payload Too Large" },
    { STATUS_URI_TOO_LONG, "URI Too Long" },
    { STATUS_UNSUPPORTED_MEDIA_TYPE, "Unsupported Media Type" },
    { STATUS_RANGE_NOT_SATISFIABLE, "Range Not Satisfiable" },
    { STATUS_EXPECTATION_FAILED, "Expectation Failed" },
    { STATUS_IM_A_TEAPOT, "I'm a teapot" },
    { STATUS_MISDIRECTED_REQUEST, "Misdirected Request" },
    { STATUS_UNPROCESSABLE_ENTITY, "Unprocessable Entity" },
    { STATUS_LOCKED, "Locked" },
    { STATUS_FAILED_DEPENDENCY, "Failed Dependency" },
    { STATUS_TOO_EARLY, "Too Early" },
    { STATUS_UPGRADE_REQUIRED, "Upgrade Required" },
    { STATUS_PRECONDITION_REQUIRED, "Precondition Required" },
    { STATUS_TOO_MANY_REQUESTS, "Too Many Requests" },
    { STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE, "Request Header Fields Too Large" },
    { STATUS_UNAVAILABLE_FOR_LEGAL_REASONS, "Unavailable For Legal Reasons" },

    { STATUS_INTERNAL_SERVER_ERROR, "Internal Server Error" },
    { STATUS_NOT_IMPLEMENTED, "Not Implemented" },
    { STATUS_BAD_GATEWAY, "Bad Gateway" },
    { STATUS_SERVICE_UNAVAILABLE, "Service Unavailable" },
    { STATUS_GATEWAY_TIMEOUT, "Gateway Timeout" },
    { STATUS_HTTP_VERSION_NOT_SUPPORTED, "HTTP Version Not Supported" },
    { STATUS_VARIANT_ALSO_NEGOTIATES, "Variant Also Negotiates" },
    { STATUS_INSUFFICIENT_STORAGE, "Insufficient Storage" },
    { STATUS_LOOP_DETECTED, "Loop Detected" },
    { STATUS_NOT_EXTENDED, "Not Extended" },
    { STATUS_NETWORK_AUTHENTICATION_REQUIRED, "Network Authentication Required" },
};
#endif /* EXTENDED_STATUS_CODES */
#endif // __ERROR_H__